- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore: agignore
    ~/.aria2/aria2.conf: aria2.conf
    ~/.axelrc: axelrc
    ~/.dotfiles: ''
    ~/.ipython/profile_default/ipython_kernel_config.py:
      ipython/profile_default/ipython_kernel_config.py
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.gnupg/gpg.conf: gpg.conf
    ~/.hgrc: hgrc
    ~/.inputrc: inputrc
    ~/.rtorrent.rc: rtorrent.rc
    ~/.screenrc: screenrc
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/.zsh: zsh
    ~/.zshrc: zshrc

- shell:
  - mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads
  - git update-submodules # after linking ~/.gitconfig
